# Homework 3
## CS 344
## Elizabeth Koning

### Problem 1

Creating a neural network for the XOR function is only possible for multi-layered neural networks with non-linear activation functions.

With a single layered network, it is impossible. A neuron evaluation uses activations and weights to compare against an activation function, such as a threshold. With XOR, there is no single threshold that can include both true values and neither false. If the threshold includes both of the values we want to be true, it will give the same results as OR and the True, True case will be included. However, we cannot raise it higher because then we exclude both of the cases that we want to result in True.

In short, XOR is not linearly separable, so no linear model can learn the XOR function.

In class, we saw how we could do it with backpropogation or with a multiple layered network.

With a multiple layered network using a step function, we can use AND and OR to get to XOR. It would look like:

![](https://lh3.googleusercontent.com/v1x38cgc3h1f10qMWvha68YlTgC5951PVFgXTkcjao4jDhQLt0FrWKk_FXW9porL-uEcpXFU9HYYd6A_Ou-SZ_VlLPSq8m5RPan6-LPIcXZ2ajF-slgBZCb_t8LVRZPZHp8GHP3EUwulyCJy6kaoz_usLWs5Z52QkCoh2sVuA9BATc2O_AH8Ys5PGZsJ2-984qhEfXSQYezQY-Ex6xmL_WBNvijNAvPmsns_LFNBMukvoydQoUe7PO68EPdhwz5jpgiHCezpxGrwXxrXuqeWOneny_lNc6yB-LkjbmBaF6FWBSkgioILIqn0LXTq9xF_LYLDc1COwF63ax-GMR1LutuuPPPEXh9hR0X-EGc2P128Muox6SnVFqDfEeKuXRw0UlWbeUC9yE5GreFGSD3Ac9WTWVt-BMzQyoKo3DSVdMnPzD2AM1EWufTde2aCeyDUvpaKJhlNqmNUbWCTiqSASRXCkkYLaxrrZpJ4nD9GKmUiUEIzqcXP1gbxwJj0WhF68yJz8lB-8cJlZcRwwEwkMNFoABsKntI2MWaaEQGPJ9hekVAKCMpnK9ZWdO1qsUL0B97w5SsoAXruOpvKXL5lTm7n158Hj7Pmx-A3DGLVA82i9Ug4g0R_t98va4pAi1FWdFBHs5i9hkpTfMkcTC8R1fGfJPfuMQTGy7M---X7uIhVmXwRNCf0uceEy7fPl4L3p-yA1M-pCqRMro1skNxc6059=w720-h959-no)

### Problem 2

First, we need to load in the data set and import the applicable packages

In [42]:
import pandas as pd
import numpy as np
from keras.datasets import boston_housing

(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

a. We can compute the dimensions of the data structures

In [43]:
print("x_train shape: ", x_train.shape)
print("y_train shape: ", y_train.shape)
print("x_test shape:  ", x_test.shape)
print("y_test shape:  ", y_test.shape)

x_train shape:  (404, 13)
y_train shape:  (404,)
x_test shape:   (102, 13)
y_test shape:   (102,)


b. Next, we can create the testing, training, and validation sets. We already having testing and training sets, we just need to create a validation set as well.

It could work well to have testing and validation datasets of the same size. Halving the testing set would leave us with only 51 examples for training and 51 for validation, so I'll take them from the training data instead.

According to the Keras documentation, some of its methods do the training/validation split within the modeling function. Depending on what we were doing, we could also have the option of telling Keras we want 20% of our training data to be used for validation.

In [44]:
x_val = x_train[0:102]
x_train = x_train[102:]
y_val = y_train[0:102]
y_train = y_train[102:]

print("x_train shape: ", x_train.shape)
print("y_train shape: ", y_train.shape)
print("x_val   shape: ", x_val.shape)
print("y_val   shape: ", y_val.shape)
print("x_test  shape: ", x_test.shape)
print("y_test  shape: ", y_test.shape)

print(x_test[1])

x_train shape:  (302, 13)
y_train shape:  (302,)
x_val shape:    (102, 13)
y_val shape:    (102,)
x_test shape:   (102, 13)
y_test shape:   (102,)
[1.2329e-01 0.0000e+00 1.0010e+01 0.0000e+00 5.4700e-01 5.9130e+00
 9.2900e+01 2.3534e+00 6.0000e+00 4.3200e+02 1.7800e+01 3.9495e+02
 1.6210e+01]


c. Next, we can create a synthetic feature that could be useful.

From the Keras documentation, it is not clear what the features we already have are. I found a list here: https://www.kaggle.com/c/boston-housing

One potentially useful synthetic feature would be multiplying "rad" (index of accessibility to radial highways) by "dis" (weighted mean of distances to five Boston employment centres) to get a more complete picture of the commuting and travel situation.

"rad" is the ninth feature, and "dis" is the eighth, so if the order Kaggle lists matches the dataset, they will be using indices 7 and 8, and we want to put our synthetic feature in column 13.

Keras does not have the features associated with their names.

In [49]:
print(x_train[:][7].shape)
print(x_train[])
travel = x_train[7] * x_train[8]
travel = travel.reshape(1,-1) # reshape to be one column
print(travel.shape)
x_train = np.append(x_train, travel, axis=0)
print("x_train shape: ", x_train.shape)


(13,)
(1, 13)
x_train shape:  (306, 13)


In [50]:
from sklearn.datasets import load_boston
boston = load_boston()
print(boston.data.shape)

X, y = boston['data'], boston['target']

(506, 13)


In [52]:
print(boston['data'])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
